### ISSUE TITLE
Update dependency from autoprefixer-core to autoprefixer

### ISSUE THREAD

**Issue by danrichman** [lasso-js/lasso-autoprefixer#2]
Looks like `autoprefixer-core` has been deprecated. The code should now require `autoprefixer` instead.

From the [autoprefixer-core](https://github.com/ai/autoprefixer-core) page:

> `autoprefixer-core` was deprecated, use `autoprefixer` instead
> Packages `autoprefixer` and `autoprefixer-core` was merged in 6.0 release. So please replace `autoprefixer-core` to `autoprefixer` in your package.json and code.

**Comment by patrick-steele-idem** [comment]
Thanks for opening the issue. Would you be interested in testing and submitting a fix? I'm not using this module at the moment. Thanks again!

**Comment by danrichman** [comment]
I'd be happy to. Coming right up.

**Comment by patrick-steele-idem** [comment]
Hey @merwan7, can you please add me as an owner for this npm module so that I can publish a new version with @danrichman's changes?:

```
npm owner add pnidem lasso-autoprefixer
```

Thanks!

**Comment by merwan7** [comment]
Sorry about the delay guys, was traveling for the past couple of weeks w/ spotty access.
Just added you as a maintainer @patrick-steele-idem 

Thanks for the PR @danrichman !

**Comment by merwan7** [comment]
pushed 2.0.0 to npm registry
